name: ([Release_Profile.gif])

on: 'Request_Change'
push: 'Acceptance'
branches: '[GenerativeImageFile].gif'
*pull_request: "Customize your Repository Management tab"
 
 types: [opened, reopened, synchronize, upload(1mp]
 workflow_dispatch: action release drafter .gif

jobs:
  release-drafter:
    uses: homebridge/.github/.github/workflows/release-drafter.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
